
variable "service_account_key_file" {
  type    = string
  default = "key.json"
}

source "googlecompute" "autogenerated_1" {
  account_file = "account.json"
  image_name   = "ubuntu-1804-dev-e516"
  project_id   = "${var.google_project_id}"
  source_image = "ubuntu-1804-bionic-v20180911"
  ssh_username = "packer"
  zone         = "us-central1-a"
}

# 1 error occurred upgrading the following block:
# unhandled "clean_resource_name" call:
# there is no way to automatically upgrade the "clean_resource_name" call.
# Please manually upgrade to use custom validation rules, `replace(string, substring, replacement)` or `regex_replace(string, substring, replacement)`
# Visit https://packer.io/docs/templates/hcl_templates/variables#custom-validation-rules , https://www.packer.io/docs/templates/hcl_templates/functions/string/replace or https://www.packer.io/docs/templates/hcl_templates/functions/string/regex_replace for more infos.

source "yandex" "autogenerated_2" {
  disk_type                = "network-ssd"
  folder_id                = "${var.folder_id}"
  image_description        = "Test image nginx"
  image_family             = "ubuntu-web-server"
  image_name               = "ubuntu-2004-lts-nginx-{{ clean_resource_name `${timestamp()}` }}"
  service_account_key_file = "${var.service_account_key_file}"
  source_image_family      = "ubuntu-2004-lts"
  ssh_username             = "ubuntu"
  use_ipv4_nat             = true
}

build {
  sources = ["source.googlecompute.autogenerated_1", "source.yandex.autogenerated_2"]

  provisioner "shell" {
    inline = ["echo 'updating apt cache'", "sudo apt update -y", "sudo apt install -y nginx nano git", "sudo systemctl enable nginx", "curl localhost"]
  }

}
